# Usar una imagen base de OpenJDK (con Java 21, que es la versión especificada en tu POM)
FROM openjdk:21-jdk-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo JAR de la aplicación (asegúrate de que tu archivo JAR se genera al hacer `mvn package`)
COPY target/calendario-0.0.1-SNAPSHOT.jar calendario.jar

# Exponer el puerto en el que la aplicación se ejecutará
EXPOSE 8080

# Comando para ejecutar la aplicación cuando el contenedor se inicie
ENTRYPOINT ["java", "-jar", "calendario.jar"]
